feat: handle pagecall events
pagecall/flutter_pagecall pull request #3
Opened 2023-07-05 12:48 UTC by parkjurung

1. ios-sdk, android-sdk 최신화 (0.0.15, 0.0.19)
2. onMessage, onLoaded, onTerminated 를 flutter 사용자가 받을 수 있도록 함

iOS에서는 TerminateReason을 stringify할 적절한 방법을 찾지 못하여 우선 nil 보내도록 하고 마무리함.

2023-07-05 12:53 UTC, parkjurung commented
android에서는 https://github.com/pplink/pagecall/pull/3227 가 배포되어야 정상작동하게 됩니다.

2023-07-05 13:03 UTC, js-seo commented on ios/Classes/FlutterPagecallView.swift
> +        self.channel?.invokeMethod("onTerminated", arguments: nil) // TODO: pass reason
이렇게 하면 됩니다!

```swift
switch reason {
  case .internal:
    self.channel?.invokeMethod("onTerminated", arguments: "internal")
  case .other(let reasonString): // Unwrap 해서 그 값을 reasonString에 담음
    self.channel?.invokeMethod("onTerminated", arguments: reasonString)
}
```

2023-07-05 13:08 UTC, parkjurung commented on ios/Classes/FlutterPagecallView.swift
> +        self.channel?.invokeMethod("onTerminated", arguments: nil) // TODO: pass reason
잘 작동하는 것 확인했습니다!

2023-07-05 13:24 UTC, js-seo approved these changes

2023-07-05 14:07 UTC, taemini requested changes

2023-07-05 14:07 UTC, taemini commented on android/src/main/kotlin/com/pagecall/pagecall_flutter/FlutterPagecallView.kt
> +                    channel.invokeMethod("onTerminated", reason.toString())
[Minor]
iOS와 똑같이 동작하게 만드는 것이 좋을 것 같습니다.
```suggestion
                    String reasonString = reason.getValue();
                    if (reason == TerminationReason.OTHER) {
                      reasonString = reason.getOtherReason();
                    }
                    channel.invokeMethod("onTerminated", reasonString)
```
이렇게 하면 iOS처럼 Reason.Other일 때 "other"이 아니라 "external"을 얻어낼 수 있습니다.

2023-07-06 00:29 UTC, parkjurung commented on android/src/main/kotlin/com/pagecall/pagecall_flutter/FlutterPagecallView.kt
> +                    channel.invokeMethod("onTerminated", reason.toString())
[fix: pass terminate reason on android](https://github.com/pagecall/flutter-pagecall/pull/3/commits/0484017061ebb44552ad93e147327bfbd655a941) 에서 적용했고 잘 작동하는 것 확인했습니다.

2023-07-06 04:05 UTC, taemini commented on android/src/main/kotlin/com/pagecall/pagecall_flutter/FlutterPagecallView.kt
> +                    channel.invokeMethod("onTerminated", reason.toString())
아아 굳굳

2023-07-06 04:05 UTC, taemini approved these changes

2023-07-06 04:07 UTC, merged